services:
  mysql:
    image: mysql:8.0
    container_name: jokes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jokes_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  joke-service:
    build:
      context: .
      dockerfile: ./joke-service/Dockerfile
    container_name: joke_service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      JOKE_SERVICE_DB_ENGINE: MYSQL
      JOKE_SERVICE_DB_HOST: mysql
      JOKE_SERVICE_DB_USER: root
      JOKE_SERVICE_DB_PASSWORD: root
      JOKE_SERVICE_DB_NAME: jokes_db
      JOKE_SERVICE_PORT: 3000
    ports:
      - "3000:3000"

  etl-service:
    build:
      context: .
      dockerfile: ./etl-service/Dockerfile
    container_name: etl_service
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ETL_SERVICE_DB_ENGINE: MYSQL
      ETL_SERVICE_PORT: 3001
      ETL_SERVICE_DB_HOST: mysql
      ETL_SERVICE_DB_USER: root
      ETL_SERVICE_DB_PASSWORD: root
      ETL_SERVICE_DB_NAME: jokes_db
      ETL_SERVICE_RABBITMQ_URL: amqp://10.10.1.30:5672
      ETL_SERVICE_MODERATED_QUEUE: moderated
      ETL_SERVICE_TYPE_UPDATE_EXCHANGE: type_update
    ports:
      - "3001:3001"

volumes:
  mysql_data: