services:
  kong:
    image: kong:3.6
    container_name: jokes_kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:80, 0.0.0.0:443 ssl"
      KONG_ADMIN_LISTEN: "127.0.0.1:8001"
      KONG_SSL_CERT: /usr/local/kong/certs/server.crt
      KONG_SSL_CERT_KEY: /usr/local/kong/certs/server.key
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8001:8001"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
      - ./kong/certs:/usr/local/kong/certs:ro