services:
  moderate-service:
    image: ${MODERATE_IMAGE}
    container_name: moderate_service
    restart: always
    environment:
      MODERATE_SERVICE_PORT: ${MODERATE_SERVICE_PORT}
      TYPES_CACHE_FILE: ${TYPES_CACHE_FILE}
      INITIAL_TYPES_FILE: ${INITIAL_TYPES_FILE}
      RABBITMQ_URL: ${RABBITMQ_URL}
      SUBMIT_QUEUE: ${SUBMIT_QUEUE}
      MODERATED_QUEUE: ${MODERATED_QUEUE}
      TYPE_UPDATE_EXCHANGE: ${TYPE_UPDATE_EXCHANGE}
      MOD_TYPE_UPDATE_QUEUE: ${MOD_TYPE_UPDATE_QUEUE}
    volumes:
      - moderate_cache:/app/cache
    ports:
      - "3100:3100"

volumes:
  moderate_cache: