services:
  submit-service:
    build:
      context: .
      dockerfile: ./submit-service/Dockerfile
    container_name: submit_service
    restart: always
    environment:
      SUBMIT_SERVICE_PORT: 3200
      TYPES_CACHE_FILE: /app/cache/types-cache.json
      INITIAL_TYPES_FILE: /app/defaults/types-cache.json
      RABBITMQ_URL: amqp://10.10.1.30:5672
      SUBMIT_QUEUE: submit
      MODERATED_QUEUE: moderated
      TYPE_UPDATE_EXCHANGE: type_update
      SUB_TYPE_UPDATE_QUEUE: sub_type_update
      MOD_TYPE_UPDATE_QUEUE: mod_type_update
    volumes:
      - submit_cache:/app/cache
    ports:
      - "3200:3200"

volumes:
  submit_cache: